name = "gemini"
main = "src/worker.mjs"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]
keep_vars = true
[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true